#########################
# Directories and files
#########################
WORKING_DIR: "" #This will serve as the output directory
WORKFLOW_DIR: "path/to/gene_catalog_pipeline" # This should be the path to the gene_catalogue_pipeline workflow directory obtained from this repository
SAMPLE_NAMES: "" # A file containing the list of metagenomic sample names to apply the workflow too. Note that the contig files must be names as SAMPLE_NAME.fa
CONTIGS_DIR: "" # Path to the directory containing the metagenomic contig files
OUT_PREFIX: "" # Output prefix to append to filenames (i.e. a project name)

# EXAMPLE EXECUTION
# snakemake \
#   -n \
#   -s scripts/gene_catalog_pipeline/gene_catalog_pipeline.smk \
#   --configfile scripts/gene_catalog_pipeline/config.yaml \
#   --profile scripts/profile/ \
#   --use-conda \
#   --rerun-incomplete
