#########################
# Directories and files
#########################
GENE_CATALOG_DIR: "" # Location of the directory containing the gene catalogue that was produced from the gene_catalogue_pipeline workflow
WORKING_DIR: "" # Output directory - note that if you plan to run this workflow on both metagenomes and metatranscriptomes, then I would suggest to set this to e.g. 'MG_analysis' for your metagenome samples and then change to 'MT_analysis' for your metatranscriptome samples
REFERENCE: "" # Gene catalogue representatives fasta file (in nucleotide format)
WORKFLOW_DIR: "" # Path to this directory (gene_coverage_pipeline directory)
SAMPLE_NAMES: "" # File containing list of sample names
READ_DIR: "" # Path to directory containing the R1 and R2 metagenomic reads used to build the assemblies. Note that these files must be named SAMPLE_NAME_1.fa.gz and SAMPLE_NAME_2.fa.gz
OUT_PREFIX: "" # Prefix for output files (i.e. project name)


#########################
# Execution code
#########################

# snakemake -n -s 01code/gene_coverage_pipeline/gene_coverage_pipeline.smk --configfile 01code/gene_coverage_pipeline/config.yaml --profile 01code/profile/ --use-conda --rerun-incomplete
